---
version: '3.8'

services:
    tool-like-nestjs:
        container_name: tool-like-nestjs
        build:
            context: .
            dockerfile: ./Dockerfile
        ports:
            - 3000:3000
